name: Deploy Nightly Demo App

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron:  '0 3 * * *' # every day at 3 am UTC

jobs:
  deploy-nightly-demo-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
              
      - run: npm ci
      - run: npm run bootstrap-no-hoist
      - run: npm run build
      - run: npm run test
      - run: npm run docs
      - run: npm run build-demo
      - name: Copy demo
        run: cp -r packages/splitview-demo/dist output/build
      - name: Copy docs
        run: cp -r packages/splitview/typedocs output/docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: outputt # The folder the action should deploy.
          TARGET_FOLDER: .
          CLEAN: true # Automatically remove deleted files from the deploy branch