name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - uses: actions/cache@v2
            with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
          

            - run: npm install -g gulp-cli
            - run: npm install -g lerna
            - run: npm install -g codecov
            - run: npm ci
            - run: lerna bootstrap --hoist
            - run: npm run build
            - run: npm test
            - run: codecov
              env:
                  CI: true
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
